spring:
  sleuth:
    sampler:
      probability: 0.1
  application:
    name: order-service
  rabbitmq:
    host: 192.168.88.133
    port: 5672
    username: admin
    password: admin

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.inetutils.preferred-networks}:${server.port}
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka

feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

---
spring:
  profiles: order1

server:
  port: 8201

---
spring:
  profiles: order2

server:
  port: 8202
