spring:
  application:
    name: config-server
  profiles:
    active: native
  rabbitmq:
    host: 192.168.88.133
    port: 5672
    username: admin
    password: admin

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
#      git:
#        uri: https://github.com/a1121323395/sp-config
#        username:
#        password:
#        search-paths: config

server:
  port: 6001

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh